### ISSUE TITLE
Project page where screenshot is displayed.

### ISSUE THREAD

**Issue by berheg** [HackYourFuture-CPH/FP-annotatetheweb-class10#134]
Project page where screenshot is displayed and includes annotation functionality. The preview of the page differ weather the user is authorized or not and the user has already annotations and comments.
Consists the following components:
-Navbar 
-ProfileSummary
-SidebarMenu
-CommentBox
Check it here: https://www.figma.com/file/QYeFmfAU7XAaewnskogsxH/Class10-Final-Project-Mockups?node-id=0%3A1

**Comment by OlkaA** [comment]
Done in #180
