### ISSUE TITLE
Storybook: Title component

### ISSUE THREAD

**Issue by bytewiz** [HackYourFuture-CPH/FP-annotatetheweb-class10#14]
When I open every single page on the website, I want to be able to see the Title, so I can identify the title/name of the website that I am in
![image](https://user-images.githubusercontent.com/16811871/69481864-5d431180-0e15-11ea-9160-dd5445b14389.png)

Create the Title storybook component that can be used across the project and style it. Make sure that it uses the right font.
The logo should also redirect to the Homepage so if the user is navigating in other pages he/she can go back to the homepage

**Comment by laila1222** [comment]
Done
