### ISSUE TITLE
Create a creative 404 page

### ISSUE THREAD

**Issue by laila1222** [HackYourFuture-CPH/FP-annotatetheweb-class10#156]
Create a creative 404 page that is related to CodeArt. 
Examples: https://www.google.com/search?q=funny+404+pages&sxsrf=ACYBGNSaOhrzK8ZIp6m-Y9ys0ez3UAl05A:1574854938578&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjB7L7pp4rmAhVJxosKHWBbBgkQ_AUoAXoECAsQAw&biw=1620&bih=938

**Comment by bytewiz** [comment]
[feature#156/create-404-page](https://github.com/HackYourFuture-CPH/FP-annotatetheweb-class10/tree/feature%23156/create-404-page)

**Comment by zkwsk** [comment]
Cloased as it is being handled under: https://github.com/HackYourFuture-CPH/FP-annotatetheweb-class10/issues/191
