### ISSUE TITLE
Make The 404 page responsive

### ISSUE THREAD

**Issue by rakhshanda-rashid** [HackYourFuture-CPH/FP-annotatetheweb-class10#159]
404 error page is already created can be access on this branch feature#156/create-404-page .But it is not responsive yet
.Use the above branch to make it responsive ..

**Comment by bytewiz** [comment]
[feature#156/create-404-page](https://github.com/HackYourFuture-CPH/FP-annotatetheweb-class10/tree/feature%23156/create-404-page)

**Comment by zkwsk** [comment]
Closed as it is being handled under: https://github.com/HackYourFuture-CPH/FP-annotatetheweb-class10/issues/191
