### ISSUE TITLE
Storybook: Footer component

### ISSUE THREAD

**Issue by bytewiz** [HackYourFuture-CPH/FP-annotatetheweb-class10#16]
When I open every single page on the website, I want to be able to check the credits for HYF and CodeArt on the Footer, so I can click and access each website.

![image](https://user-images.githubusercontent.com/16811871/69481897-a72bf780-0e15-11ea-8afd-fede3ccf2612.png)
 
Create the Links components with the appropriate style and the Footer component that includes them.

**Comment by laila1222** [comment]
Done
