### ISSUE TITLE
Storybook: Sign up form

### ISSUE THREAD

**Issue by bytewiz** [HackYourFuture-CPH/FP-annotatetheweb-class10#17]
When I click the register button, I want to be able to register using a Sign Up Form, so I can register/sign up on the website using a 3rd party.

![image](https://user-images.githubusercontent.com/16811871/69481913-c88ce380-0e15-11ea-8d38-e5a2739c6111.png)

The sign up should be a form component and it must include a Title, Buttons that provide options for the type of sign up, Input text box for Full name, Username, Email and Password, and a Create Account button

**Comment by laila1222** [comment]
Done
