### ISSUE TITLE
Storybook: Sign in form

### ISSUE THREAD

**Issue by bytewiz** [HackYourFuture-CPH/FP-annotatetheweb-class10#18]
When I click the Login button, I want to be able to login using a Login Form, so I can signin using a 3rd party.

![image](https://user-images.githubusercontent.com/16811871/69481925-e22e2b00-0e15-11ea-9bac-001aebefb557.png)

The Sign in component should be a form that must include a Title, Buttons that provide options for the type of login, Input text box for Email and Password, and a Login button

**Comment by laila1222** [comment]
Done
