### ISSUE TITLE
Storybook: Sidebar menu

### ISSUE THREAD

**Issue by bytewiz** [HackYourFuture-CPH/FP-annotatetheweb-class10#19]
When I am logged in, I want to be able to use a Sidebar menu, so I can work with the operations that the control panel provides me with.
 
![image](https://user-images.githubusercontent.com/16811871/69481948-08ec6180-0e16-11ea-85ed-2f8809b12508.png)

The sidebar component must include buttons for Search, Project, Email, Comments, Share, User Settings.

**Comment by laila1222** [comment]
Component done, 
Merged into develop
