### ISSUE TITLE
Make work to get screenshot image using screenshot key from home page

### ISSUE THREAD

**Issue by berheg** [HackYourFuture-CPH/FP-annotatetheweb-class10#197]
- Use the screenShot_key from home page using context or localstorage  to project page to get screenshot image
- Make sure routering from home page to project page passes the screenShot_key using context or localstorage
- Use the screeshot_key in the screenshotURL and request screenshotImage when it is ready pass to the annotation component

**Comment by laila1222** [comment]
Done
