### ISSUE TITLE
Storybook: Buttons

### ISSUE THREAD

**Issue by dpfernandes** [HackYourFuture-CPH/FP-annotatetheweb-class10#26]
When I use the navigation, I want to be able to use the buttons, so I can choose the different options.

<img width="388" alt="Screenshot 2019-11-24 at 20 34 12" src="https://user-images.githubusercontent.com/6642037/69500264-e16ec500-0ef9-11ea-8c87-03f6d4b3208f.png">

Create the Link buttons for Annotate, About and Login and make sure that once you click on it, the button becomes underlined.

Create a Register button with round edges.

**Comment by laila1222** [comment]
Done
