### ISSUE TITLE
Endpoint to Create a Screenshot

### ISSUE THREAD

**Issue by dpfernandes** [HackYourFuture-CPH/FP-annotatetheweb-class10#32]
When I see a webpage that I want to annotate, I want to be able to make a screenshot,so I can work on it later and share it.

<img width="986" alt="Screenshot 2019-11-25 at 04 27 13" src="https://user-images.githubusercontent.com/6642037/69511681-71842d00-0f41-11ea-838d-593c3895c9e2.png">

Create an endpoint that takes the URL and the WIDTH from the frontend (search bar component) and uses the POST operation of the web service provide by CodeArt → Check the documentation about the webservice on https://api.annotatetheweb.com/swagger/ui/index#!/Screenshot/Screenshot_CheckStatusOnScreenshot
Create a table using a KnexJS script that matches the Diagram on the README file.
Use the response from the previous endpoint and KnexJS script to CREATE/Update the the table where we store the Screenshot information.

**Comment by laila1222** [comment]
Done
