### ISSUE TITLE
Endpoint to view a Screenshot

### ISSUE THREAD

**Issue by dpfernandes** [HackYourFuture-CPH/FP-annotatetheweb-class10#34]
When I want to work on my screenshot annotation, I want to be able to see it on my screen so I see it or  make new annotations.

Make sure you already have demo data on the Screenshot table and if not talk to the group/person that is working on Issue/Task #32 

Create an endpoint that calls GET operation on the web service provided by CodeArt using the specific KEY that was passed through the endpoint that calls the DB.

<img width="975" alt="Screenshot 2019-11-25 at 04 31 13" src="https://user-images.githubusercontent.com/6642037/69512830-e35e7580-0f45-11ea-89a2-67031b2d8f32.png">

And will retrieve a JSON object like this:

![Screenshot 2019-11-24 at 15 03 37](https://user-images.githubusercontent.com/6642037/69512849-f2452800-0f45-11ea-9f8c-8f6fac42e4a0.png)

Check the swagger for the web service here https://api.annotatetheweb.com/swagger/ui/index

**Comment by laila1222** [comment]
Done, merged into develop.
