### ISSUE TITLE
Endpoint to Delete an Annotation

### ISSUE THREAD

**Issue by dpfernandes** [HackYourFuture-CPH/FP-annotatetheweb-class10#37]
When I no longer need an annotation, I want to be able to delete it, so I only have the annotations that I need.

Create an endpoint for using nodejs, knex which can delete a record in the database table which is for a the specific annotation, you wish to delete/remote. So you have to use an `DELETE` statement to update it in the database using knex, check database diagram for table references: https://dbdiagram.io/d/5dd6b6f7edf08a25543e3621

**Comment by bytewiz** [comment]
@azinkamran why is there no pull request for this one yet? :)
