### ISSUE TITLE
Firebase authentication

### ISSUE THREAD

**Issue by dpfernandes** [HackYourFuture-CPH/FP-annotatetheweb-class10#74]
Using Niels explanation and Firebase account that Mohammed Reza created you should enable authentication for Google, Facebook and Twitter and create endpoints that allow you to retrieve the authentication token.

**Getting started with firebase authentication for web**
https://firebase.google.com/docs/auth/web/start follow the guide to get it installed (there is a link) and read the entire page before you start!!

**Sign in existing users with firebase**
https://firebase.google.com/docs/auth/web/start#sign_in_existing_users

**Sign up new users with firebase**
https://firebase.google.com/docs/auth/web/start#sign_up_new_users

**Manage the authentication state from firebase**
This is an observer that will get called every time a users authentication state changes (for example from not authentication to authenticated and the other way around)
https://firebase.google.com/docs/auth/web/start#set_an_authentication_state_observer_and_get_user_data

**Create a page for each sign in and sign up with the forms**

**Add the social sign methods as well**

**Google sign in**
https://firebase.google.com/docs/auth/web/google-signin

**Facebook sign in**
https://firebase.google.com/docs/auth/web/facebook-login

**Twitter sign in**
https://firebase.google.com/docs/auth/web/twitter-login

**NOTE:** that the social logins does not require sign up they handle both sign up and sign in in one 👍

**Comment by laila1222** [comment]
New issue was created
